// Self-hosted CJK web-font slicer (DESIGN_LANGUAGE §11: self-hosted, no third-party
// request). Splits each needed Japanese weight into unicode-range slices — the same
// technique Google Fonts uses for Noto Sans JP — so a browser fetches only the slices
// whose glyphs actually appear on the page. This is the fix for the LCP regression:
// the homepage was pulling ~3.7 MB of un-sliced Japanese woff2 (zen-old-mincho-700
// alone is ~2 MB) and saturating real mobile connections. woff2 is already Brotli, so
// transport gzip can't help — only cutting glyph count does.
//
// Boundaries are reused verbatim from Google's Noto Sans JP partition (scripts/
// noto-jp-ranges.json, 124 frequency-grouped buckets) so common kana/ASCII/frequent
// kanji land in tiny slices that load first; rare kanji sit in slices that most pages
// never request. Glyphs absent from our display Mincho fall back per-glyph to the
// system Mincho stack (Hiragino/Yu/Noto) — fine for an open-vocabulary records site.
//
// Source faces are the @fontsource woff2 already in devDependencies; nothing is fetched
// at build time. Output (woff2 slices + jp.css) is committed and regenerated only when
// the faces or the charset change: `pnpm run fonts:build`.

import subsetFont from 'subset-font';
import * as fontkit from 'fontkit';
import { readFileSync, writeFileSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(here, '..');
const r = (p) => resolve(webRoot, p);

// The weights we actually use (verified against the components/tokens):
//   Zen Old Mincho 700  → --font-display / record titles & H1 (DESIGN_LANGUAGE §4.1)
//   IBM Plex Sans JP 400 → body, 600 → screen headings/strong (the only sans-jp weights in use)
// Everything else the layout used to import (zen 600, sans-jp 500/700, …) is dropped.
const FACES = [
	{
		family: 'Zen Old Mincho',
		weight: 700,
		slug: 'zen-old-mincho-700',
		src: 'node_modules/@fontsource/zen-old-mincho/files/zen-old-mincho-japanese-700-normal.woff2'
	},
	{
		family: 'IBM Plex Sans JP',
		weight: 400,
		slug: 'ibm-plex-sans-jp-400',
		src: 'node_modules/@fontsource/ibm-plex-sans-jp/files/ibm-plex-sans-jp-japanese-400-normal.woff2'
	},
	{
		family: 'IBM Plex Sans JP',
		weight: 600,
		slug: 'ibm-plex-sans-jp-600',
		src: 'node_modules/@fontsource/ibm-plex-sans-jp/files/ibm-plex-sans-jp-japanese-600-normal.woff2'
	}
];

const OUT_DIR = r('src/lib/fonts/jp');
const CSS_PATH = r('src/lib/fonts/jp.css');
const buckets = JSON.parse(readFileSync(r('scripts/noto-jp-ranges.json'), 'utf8'));

// Expand a CSS unicode-range string ("U+3000-303F, U+ff01, …") into the explicit list
// of code points it covers.
function codepointsOf(rangeStr) {
	const cps = [];
	for (const tok of rangeStr.split(',')) {
		const t = tok.trim().replace(/^U\+/i, '');
		const [a, b] = t.split('-');
		const lo = parseInt(a, 16);
		const hi = b === undefined ? lo : parseInt(b, 16);
		for (let cp = lo; cp <= hi; cp++) cps.push(cp);
	}
	return cps;
}

// Fresh output dir each run so removed glyphs never leave stale slices behind.
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const cssBlocks = [
	'/* GENERATED by scripts/subset-fonts.mjs — do not edit by hand. */',
	'/* Self-hosted, unicode-range-sliced Japanese faces. Regenerate: pnpm run fonts:build */'
];
const summary = [];

for (const face of FACES) {
	const srcBuf = readFileSync(r(face.src));
	const font = fontkit.create(srcBuf);
	const present = new Set(font.characterSet); // code points this face actually contains
	let sliceCount = 0;
	let totalBytes = 0;

	for (let i = 0; i < buckets.length; i++) {
		const want = codepointsOf(buckets[i]).filter((cp) => present.has(cp));
		if (want.length === 0) continue; // face has nothing in this bucket → emit no slice

		const text = String.fromCodePoint(...want);
		const sliced = await subsetFont(srcBuf, text, { targetFormat: 'woff2' });
		const file = `${face.slug}.${i}.woff2`;
		writeFileSync(`${OUT_DIR}/${file}`, sliced);
		sliceCount++;
		totalBytes += sliced.length;

		cssBlocks.push(
			`@font-face{font-family:'${face.family}';font-style:normal;font-weight:${face.weight};` +
				`font-display:swap;src:url('./jp/${file}') format('woff2');unicode-range:${buckets[i]}}`
		);
	}

	summary.push(
		`${face.slug.padEnd(22)} ${String(sliceCount).padStart(3)} slices  ${(totalBytes / 1024).toFixed(0).padStart(5)} KB  (source ${(srcBuf.length / 1024).toFixed(0)} KB)`
	);
}

writeFileSync(CSS_PATH, cssBlocks.join('\n') + '\n');

const fileCount = readdirSync(OUT_DIR).length;
console.log('--- subset-fonts ---');
console.log(summary.join('\n'));
console.log(`total: ${fileCount} woff2 slices → ${OUT_DIR}`);
console.log(`css:   ${CSS_PATH}`);
