import type { Handle } from '@sveltejs/kit';

// Defense-in-depth response headers (A05; CWE-1021/CWE-693). The full
// Content-Security-Policy (including frame-ancestors 'none') is generated by
// kit.csp in svelte.config.js; these headers complement it: nosniff stops MIME
// confusion, X-Frame-Options backs up frame-ancestors for legacy clients, a
// no-referrer policy avoids leaking the visited path to outbound gov permalinks
// (matches the project's privacy stance), and COOP isolates the browsing context.
export const handle: Handle = async ({ event, resolve }) => {
	const response = await resolve(event);
	response.headers.set('X-Content-Type-Options', 'nosniff');
	response.headers.set('X-Frame-Options', 'DENY');
	response.headers.set('Referrer-Policy', 'no-referrer');
	response.headers.set('Cross-Origin-Opener-Policy', 'same-origin');
	return response;
};
